//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubtitleBackoffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTable
    {
        public int Key { get; set; }
        public System.DateTime LogDate { get; set; }
        public string ContentID { get; set; }
        public int EpisodeNumber { get; set; }
        public string LanguageCode { get; set; }
        public string Device { get; set; }
    }
}
