#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogAnalysis
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="subtitle")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEpisodeTable(EpisodeTable instance);
    partial void UpdateEpisodeTable(EpisodeTable instance);
    partial void DeleteEpisodeTable(EpisodeTable instance);
    partial void InsertSubtitle(Subtitle instance);
    partial void UpdateSubtitle(Subtitle instance);
    partial void DeleteSubtitle(Subtitle instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::LogAnalysis.Properties.Settings.Default.subtitleConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<EpisodeTable> EpisodeTables
		{
			get
			{
				return this.GetTable<EpisodeTable>();
			}
		}
		
		public System.Data.Linq.Table<Subtitle> Subtitles
		{
			get
			{
				return this.GetTable<Subtitle>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EpisodeTable")]
	public partial class EpisodeTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _key;
		
		private string _Id;
		
		private string _Name;
		
		private string _Image;
		
		private string _Tag;
		
		private string _PriceType;
		
		private System.Nullable<int> _PriceInWon;
		
		private string _ProgramId;
		
		private string _ProgramName;
		
		private int _MajorEpisodeNo;
		
		private System.Nullable<int> _MinorEpisodeNo;
		
		private string _ProgramGroupId;
		
		private string _ProgramGroupName;
		
		private string _ChannelId;
		
		private string _ChannelName;
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<int> _ViewCountForLastHour;
		
		private System.Nullable<int> _Ranking;
		
		private System.Nullable<int> _Streammable;
		
		private string _MessageForNotStreammable;
		
		private System.Nullable<int> _Downloadable;
		
		private string _MessageForNotDownloadable;
		
		private System.Nullable<int> _RatingAge;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkeyChanging(int value);
    partial void OnkeyChanged();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnImageChanging(string value);
    partial void OnImageChanged();
    partial void OnTagChanging(string value);
    partial void OnTagChanged();
    partial void OnPriceTypeChanging(string value);
    partial void OnPriceTypeChanged();
    partial void OnPriceInWonChanging(System.Nullable<int> value);
    partial void OnPriceInWonChanged();
    partial void OnProgramIdChanging(string value);
    partial void OnProgramIdChanged();
    partial void OnProgramNameChanging(string value);
    partial void OnProgramNameChanged();
    partial void OnMajorEpisodeNoChanging(int value);
    partial void OnMajorEpisodeNoChanged();
    partial void OnMinorEpisodeNoChanging(System.Nullable<int> value);
    partial void OnMinorEpisodeNoChanged();
    partial void OnProgramGroupIdChanging(string value);
    partial void OnProgramGroupIdChanged();
    partial void OnProgramGroupNameChanging(string value);
    partial void OnProgramGroupNameChanged();
    partial void OnChannelIdChanging(string value);
    partial void OnChannelIdChanged();
    partial void OnChannelNameChanging(string value);
    partial void OnChannelNameChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    partial void OnViewCountForLastHourChanging(System.Nullable<int> value);
    partial void OnViewCountForLastHourChanged();
    partial void OnRankingChanging(System.Nullable<int> value);
    partial void OnRankingChanged();
    partial void OnStreammableChanging(System.Nullable<int> value);
    partial void OnStreammableChanged();
    partial void OnMessageForNotStreammableChanging(string value);
    partial void OnMessageForNotStreammableChanged();
    partial void OnDownloadableChanging(System.Nullable<int> value);
    partial void OnDownloadableChanged();
    partial void OnMessageForNotDownloadableChanging(string value);
    partial void OnMessageForNotDownloadableChanged();
    partial void OnRatingAgeChanging(System.Nullable<int> value);
    partial void OnRatingAgeChanged();
    #endregion
		
		public EpisodeTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[key]", Storage="_key", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int key
		{
			get
			{
				return this._key;
			}
			set
			{
				if ((this._key != value))
				{
					this.OnkeyChanging(value);
					this.SendPropertyChanging();
					this._key = value;
					this.SendPropertyChanged("key");
					this.OnkeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="NVarChar(500)")]
		public string Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tag", DbType="NVarChar(50)")]
		public string Tag
		{
			get
			{
				return this._Tag;
			}
			set
			{
				if ((this._Tag != value))
				{
					this.OnTagChanging(value);
					this.SendPropertyChanging();
					this._Tag = value;
					this.SendPropertyChanged("Tag");
					this.OnTagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceType", DbType="NVarChar(50)")]
		public string PriceType
		{
			get
			{
				return this._PriceType;
			}
			set
			{
				if ((this._PriceType != value))
				{
					this.OnPriceTypeChanging(value);
					this.SendPropertyChanging();
					this._PriceType = value;
					this.SendPropertyChanged("PriceType");
					this.OnPriceTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceInWon", DbType="Int")]
		public System.Nullable<int> PriceInWon
		{
			get
			{
				return this._PriceInWon;
			}
			set
			{
				if ((this._PriceInWon != value))
				{
					this.OnPriceInWonChanging(value);
					this.SendPropertyChanging();
					this._PriceInWon = value;
					this.SendPropertyChanged("PriceInWon");
					this.OnPriceInWonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramId", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ProgramId
		{
			get
			{
				return this._ProgramId;
			}
			set
			{
				if ((this._ProgramId != value))
				{
					this.OnProgramIdChanging(value);
					this.SendPropertyChanging();
					this._ProgramId = value;
					this.SendPropertyChanged("ProgramId");
					this.OnProgramIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramName", DbType="NVarChar(500)")]
		public string ProgramName
		{
			get
			{
				return this._ProgramName;
			}
			set
			{
				if ((this._ProgramName != value))
				{
					this.OnProgramNameChanging(value);
					this.SendPropertyChanging();
					this._ProgramName = value;
					this.SendPropertyChanged("ProgramName");
					this.OnProgramNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MajorEpisodeNo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MajorEpisodeNo
		{
			get
			{
				return this._MajorEpisodeNo;
			}
			set
			{
				if ((this._MajorEpisodeNo != value))
				{
					this.OnMajorEpisodeNoChanging(value);
					this.SendPropertyChanging();
					this._MajorEpisodeNo = value;
					this.SendPropertyChanged("MajorEpisodeNo");
					this.OnMajorEpisodeNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinorEpisodeNo", DbType="Int")]
		public System.Nullable<int> MinorEpisodeNo
		{
			get
			{
				return this._MinorEpisodeNo;
			}
			set
			{
				if ((this._MinorEpisodeNo != value))
				{
					this.OnMinorEpisodeNoChanging(value);
					this.SendPropertyChanging();
					this._MinorEpisodeNo = value;
					this.SendPropertyChanged("MinorEpisodeNo");
					this.OnMinorEpisodeNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramGroupId", DbType="NVarChar(50)")]
		public string ProgramGroupId
		{
			get
			{
				return this._ProgramGroupId;
			}
			set
			{
				if ((this._ProgramGroupId != value))
				{
					this.OnProgramGroupIdChanging(value);
					this.SendPropertyChanging();
					this._ProgramGroupId = value;
					this.SendPropertyChanged("ProgramGroupId");
					this.OnProgramGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramGroupName", DbType="NVarChar(100)")]
		public string ProgramGroupName
		{
			get
			{
				return this._ProgramGroupName;
			}
			set
			{
				if ((this._ProgramGroupName != value))
				{
					this.OnProgramGroupNameChanging(value);
					this.SendPropertyChanging();
					this._ProgramGroupName = value;
					this.SendPropertyChanged("ProgramGroupName");
					this.OnProgramGroupNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChannelId", DbType="NVarChar(50)")]
		public string ChannelId
		{
			get
			{
				return this._ChannelId;
			}
			set
			{
				if ((this._ChannelId != value))
				{
					this.OnChannelIdChanging(value);
					this.SendPropertyChanging();
					this._ChannelId = value;
					this.SendPropertyChanged("ChannelId");
					this.OnChannelIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChannelName", DbType="NVarChar(50)")]
		public string ChannelName
		{
			get
			{
				return this._ChannelName;
			}
			set
			{
				if ((this._ChannelName != value))
				{
					this.OnChannelNameChanging(value);
					this.SendPropertyChanging();
					this._ChannelName = value;
					this.SendPropertyChanged("ChannelName");
					this.OnChannelNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewCountForLastHour", DbType="Int")]
		public System.Nullable<int> ViewCountForLastHour
		{
			get
			{
				return this._ViewCountForLastHour;
			}
			set
			{
				if ((this._ViewCountForLastHour != value))
				{
					this.OnViewCountForLastHourChanging(value);
					this.SendPropertyChanging();
					this._ViewCountForLastHour = value;
					this.SendPropertyChanged("ViewCountForLastHour");
					this.OnViewCountForLastHourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ranking", DbType="Int")]
		public System.Nullable<int> Ranking
		{
			get
			{
				return this._Ranking;
			}
			set
			{
				if ((this._Ranking != value))
				{
					this.OnRankingChanging(value);
					this.SendPropertyChanging();
					this._Ranking = value;
					this.SendPropertyChanged("Ranking");
					this.OnRankingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Streammable", DbType="Int")]
		public System.Nullable<int> Streammable
		{
			get
			{
				return this._Streammable;
			}
			set
			{
				if ((this._Streammable != value))
				{
					this.OnStreammableChanging(value);
					this.SendPropertyChanging();
					this._Streammable = value;
					this.SendPropertyChanged("Streammable");
					this.OnStreammableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageForNotStreammable", DbType="NVarChar(200)")]
		public string MessageForNotStreammable
		{
			get
			{
				return this._MessageForNotStreammable;
			}
			set
			{
				if ((this._MessageForNotStreammable != value))
				{
					this.OnMessageForNotStreammableChanging(value);
					this.SendPropertyChanging();
					this._MessageForNotStreammable = value;
					this.SendPropertyChanged("MessageForNotStreammable");
					this.OnMessageForNotStreammableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Downloadable", DbType="Int")]
		public System.Nullable<int> Downloadable
		{
			get
			{
				return this._Downloadable;
			}
			set
			{
				if ((this._Downloadable != value))
				{
					this.OnDownloadableChanging(value);
					this.SendPropertyChanging();
					this._Downloadable = value;
					this.SendPropertyChanged("Downloadable");
					this.OnDownloadableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageForNotDownloadable", DbType="NVarChar(200)")]
		public string MessageForNotDownloadable
		{
			get
			{
				return this._MessageForNotDownloadable;
			}
			set
			{
				if ((this._MessageForNotDownloadable != value))
				{
					this.OnMessageForNotDownloadableChanging(value);
					this.SendPropertyChanging();
					this._MessageForNotDownloadable = value;
					this.SendPropertyChanged("MessageForNotDownloadable");
					this.OnMessageForNotDownloadableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RatingAge", DbType="Int")]
		public System.Nullable<int> RatingAge
		{
			get
			{
				return this._RatingAge;
			}
			set
			{
				if ((this._RatingAge != value))
				{
					this.OnRatingAgeChanging(value);
					this.SendPropertyChanging();
					this._RatingAge = value;
					this.SendPropertyChanged("RatingAge");
					this.OnRatingAgeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Subtitle")]
	public partial class Subtitle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ContentID;
		
		private string _Name;
		
		private string _EpisodeNumber;
		
		private string _CategoryCode;
		
		private string _CountryCode;
		
		private string _StatusCode;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private string _URL;
		
		private string _subtitle1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnContentIDChanging(string value);
    partial void OnContentIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEpisodeNumberChanging(string value);
    partial void OnEpisodeNumberChanged();
    partial void OnCategoryCodeChanging(string value);
    partial void OnCategoryCodeChanged();
    partial void OnCountryCodeChanging(string value);
    partial void OnCountryCodeChanged();
    partial void OnStatusCodeChanging(string value);
    partial void OnStatusCodeChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void Onsubtitle1Changing(string value);
    partial void Onsubtitle1Changed();
    #endregion
		
		public Subtitle()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContentID", DbType="VarChar(30)")]
		public string ContentID
		{
			get
			{
				return this._ContentID;
			}
			set
			{
				if ((this._ContentID != value))
				{
					this.OnContentIDChanging(value);
					this.SendPropertyChanging();
					this._ContentID = value;
					this.SendPropertyChanged("ContentID");
					this.OnContentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EpisodeNumber", DbType="VarChar(4)")]
		public string EpisodeNumber
		{
			get
			{
				return this._EpisodeNumber;
			}
			set
			{
				if ((this._EpisodeNumber != value))
				{
					this.OnEpisodeNumberChanging(value);
					this.SendPropertyChanging();
					this._EpisodeNumber = value;
					this.SendPropertyChanged("EpisodeNumber");
					this.OnEpisodeNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryCode", DbType="VarChar(3)")]
		public string CategoryCode
		{
			get
			{
				return this._CategoryCode;
			}
			set
			{
				if ((this._CategoryCode != value))
				{
					this.OnCategoryCodeChanging(value);
					this.SendPropertyChanging();
					this._CategoryCode = value;
					this.SendPropertyChanged("CategoryCode");
					this.OnCategoryCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryCode", DbType="VarChar(3)")]
		public string CountryCode
		{
			get
			{
				return this._CountryCode;
			}
			set
			{
				if ((this._CountryCode != value))
				{
					this.OnCountryCodeChanging(value);
					this.SendPropertyChanging();
					this._CountryCode = value;
					this.SendPropertyChanged("CountryCode");
					this.OnCountryCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusCode", DbType="VarChar(3)")]
		public string StatusCode
		{
			get
			{
				return this._StatusCode;
			}
			set
			{
				if ((this._StatusCode != value))
				{
					this.OnStatusCodeChanging(value);
					this.SendPropertyChanging();
					this._StatusCode = value;
					this.SendPropertyChanged("StatusCode");
					this.OnStatusCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="VarChar(255)")]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this.OnURLChanging(value);
					this.SendPropertyChanging();
					this._URL = value;
					this.SendPropertyChanged("URL");
					this.OnURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="subtitle", Storage="_subtitle1", DbType="NVarChar(MAX)")]
		public string subtitle1
		{
			get
			{
				return this._subtitle1;
			}
			set
			{
				if ((this._subtitle1 != value))
				{
					this.Onsubtitle1Changing(value);
					this.SendPropertyChanging();
					this._subtitle1 = value;
					this.SendPropertyChanged("subtitle1");
					this.Onsubtitle1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
